src/python/loxi/of10/util.py
src/python/loxi/of11/util.py
src/python/loxi/of12/oxm.py
src/python/loxi/of12/util.py
src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/const.py
src/python/loxi/of13/message.py
src/python/loxi/of13/oxm.py
src/python/loxi/of13/util.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/const.py
src/python/loxi/of14/message.py
src/python/loxi/of14/oxm.py
src/python/loxi/of14/util.py

update pyloxi to floodlight/loxigen-artifacts @ 1c503031afab723babd7cbcdbac8ebf0ea7490d1

---

src/python/loxi/of14/port_desc_prop.py

update pyloxi to floodlight/loxigen-artifacts @ 7f8b06392f610bae43424f2a5ba2ec243203a865

---

tests-1.4/role_status.py

Reviewer: trivial
This is copied from the BSN role status test, only needing to change a few 
constants.

add OF 1.4 role status test

---

tests-1.4/bundle.py

tests-1.4: add bundle.Barrier testcase

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/instruction.py
src/python/loxi/of13/instruction_id.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/instruction.py
src/python/loxi/of14/instruction_id.py

Latest loxi with bsn_diable_l3 instruction.

---

tests/FuncUtils.py

allow delayed counter updates for table stats

---

src/python/loxi/of13/oxm.py
src/python/loxi/of14/oxm.py
src/python/loxi/of14/port_desc_prop.py

update pyloxi to floodlight/loxigen-artifacts @ fae5788e9a287b77b15f53d75840e6951f2150c5

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of14/bsn_tlv.py

update pyloxi to include ipv6-tlv

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/const.py
src/python/loxi/of13/message.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/const.py
src/python/loxi/of14/message.py

update pyloxi to latest

---

src/python/loxi/of12/message.py
src/python/loxi/of13/message.py
src/python/loxi/of14/message.py
src/python/oftest/controller.py

Reviewer: @rlane 
Without the controller.py change, oftest throws an AttributeError.

Update pyloxi, support of_bsn_error

---

src/python/oftest/controller.py

Check version before trying to print BSN error msg.

---

src/python/oftest/testutils.py
tests-1.3/bsn_gentable.py

Update bsn_gentable tests to expect bsn_error messages.
Reviewer: @rlane

Update verify_no_errors to raise bsn_error exceptions.

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/common.py
src/python/loxi/of13/message.py
src/python/loxi/of13/oxm.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/common.py
src/python/loxi/of14/message.py
src/python/loxi/of14/oxm.py

update pyloxi to include latest tlvs

---

tests-1.4/bsn_histogram.py

Reviewer: @harshsin 
This tests the stats requests added in floodlight/indigo#220.

tests-1.4: add bsn_histogram testcases

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of14/bsn_tlv.py

Update pyloxi to include latest bsn-tlvs

---

src/python/oftest/packet.py
src/python/oftest/testutils.py
src/python/oftest/vxlan.py

Reviewer: @kenchiang @poolakiran

Add api to construct vxlan packets

---

src/python/loxi/of10/util.py
src/python/loxi/of11/util.py
src/python/loxi/of12/oxm.py
src/python/loxi/of12/util.py
src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/const.py
src/python/loxi/of13/oxm.py
src/python/loxi/of13/util.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/const.py
src/python/loxi/of14/oxm.py
src/python/loxi/of14/util.py

Reviewer: @poolakiran
CC: @kenchiang

Latest pyloxi.

---

tests-1.3/bsn_gentable.py

Reviewer: @poolakiran
CC: @kenchiang

Expect ofp.message.bsn_gentable_error instance on gentable errors.

---

platforms/veth_inject.py

Reviewer: @jnealtowns 
For exercising dataplane ports connected to veth pairs

Add veth_inject platform

---

oft

Add xunit-suffix configuration option

---

platforms/veth_inject.py

Reviewer: @poolakiran @wilmo119 
Update veth_inject platform to generate port_map dictionary using loopback configuration and ifname-to-ofport-map files specified by platform-args.
After this change, note that the platform-args will be loopback-config-filename and ifname-to-ofport-map-filename.

Update veth_inject platform 

---

platforms/veth_inject.py

Reviewer: @poolakiran 
These changes were discussed with Ken when testing BFD. They will be used to detect the loopback testbed.

add extra fields to config

---

src/python/oftest/packet.py

Add variables for NDP to packet.py

---

src/python/oftest/packet.py
src/python/oftest/testutils.py

Reviewer: @poolakiran @harishraghavendra
to generate RS/RA, NS/NA, echo req/reply, dest unreachable, and time exceeded messages

Extend simple_icmpv6_packet 

---

platforms/veth_sim.py

Reviewer: @wilmo119 
CC: @kenchiang

Add veth_sim platform.

---

platforms/knet_inject.py

Reviewer: @poolakiran @harishraghavendra 
Use a new platform for the knet case

SWL-6033 create a new knet_inject platform

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/const.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/const.py
src/python/loxi/of15/bsn_tlv.py
src/python/loxi/of15/const.py

Updated TLVs

---

src/python/oftest/afpacket.py
src/python/oftest/dataplane.py

Reviewer: @poolakiran @kenchiang 
Handle port removal case - socket will return 0 and with special error code

handle port removal case

---

src/python/loxi/of13/bsn_tlv.py
src/python/loxi/of13/const.py
src/python/loxi/of14/bsn_tlv.py
src/python/loxi/of14/const.py
src/python/loxi/of15/bsn_tlv.py
src/python/loxi/of15/const.py

Latest pyloxi
